services:
  web1:
    build: .
    restart: always
    hostname: web1
    expose:
      - 8080
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  web2:
    build: .
    restart: always
    hostname: web2
    expose:
      - 8080
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'
  
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: rinha
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 15s
      timeout: 25s
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '1.5GB'

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web1
      - web2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'